### ISSUE TITLE
Deploy with CI

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/cdts-sgdc#9]
Use CI to deploy `dist` folder to servers

Use TravisCI to deploy to azure and teamsite

**Comment by shawnthompson** [comment]
Brainstorming...  Workflow

Change to be made... 
1. `$ git pull origin master`
2. `$ git checkout -b new-change`
3. make change
4. build package
5. previous change locally
6. `$ git commit -am "my new change, related #issue"`
7. `$ git push origin new-change`
8. create merge / pull requests into *master*
9. CI runs test
10. If test pass, able to merge
11. Merge *new-change*
12. CI run build and creates *dist* folder of artifacts
13. CI deploys contents of *dist* folder into *master* folder on domain (https://cdts.canada.ca/master/) using AZURE
    
Release to be made
1. new *tag* made on master branch with release name (eg: v1.0.0)
2. CI run build and creates *dist* folder of artifacts
3. CI deploys contents of *dist* folder into a folder with the same name as the *tag* (https://cdts.canada.ca/v1.0.0/) 

Thoughts @pabrams

**Comment by duboisp** [comment]
To help you, we already have something similar setup for wet-boew when the TravisCI build is triggered on the creation of a tag or when commit is merged to master. 
The build script do the following
* compile wet-boew
* Clone repo which contains the compiled files
* Take the files in the builded dist and do a commit in the repository in the master branch and create a corresponding tag if needed
* Those change get published in teh wet-boew webpage via the gh-pages

All that logic is in the grunt.coffee file.

**Comment by shawnthompson** [comment]
So far...
* created a repo to host the `./dist` folder [/wet-boew/cdts-sgdc-cdn](https://github.com/wet-boew/cdts-sgdc-cdn)
* gave @wet-boew-bot writing access to the repo
* created a personal access token from the @wet-boew-bot account
* created an Environment Variables in the [Travis-ci cdts project](https://travis-ci.org/wet-boew/cdts-sgdc/settings) **$GITHUB_TOKEN**
* added a script that uses [node gh-pages](https://www.npmjs.com/package/gh-pages) to deploy the `./dist` folder to a gh-pages branch

Stay tuned

**Comment by shawnthompson** [comment]
Using Travis to deploy to the cdn repo:

```
deploy:
  provider: pages // used to deploy with git and gh-pages
  github_token: $GH_TOKEN // secret token used to give permission to wet-boew-bot to deploy to our repo
  local_dir: ./dist/ // directory to be deployed
  repo: wet-boew/cdts-sgdc-cdn //which repo to deploy to
  email: $GIT_AUTHOR_EMAIL // email to be used when committing the deploy 
  name: $GIT_AUTHOR_NAME // name to be used when committing the deploy
  skip_cleanup: true // stops Travis from deleting the ./dist/ folder before deployment
  target_branch: 1.0.0-pre-alpha // branch to create or deploy to
```
